/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/TYRAIAabnCu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'
import { Prata } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

prata({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function contabilidad() {
  return (
    (<div className="w-full max-w-4xl mx-auto py-12 px-4 md:px-6">
      <div className="grid gap-8">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Módulo de Contabilidad</h1>
          <p className="mt-4 text-muted-foreground">
            El departamento de contabilidad es responsable de registrar, procesar y analizar la información financiera
            de la empresa. Sus principales funciones incluyen:
          </p>
        </div>
        <div className="space-y-6">
          <div className="p-6 bg-muted rounded-lg">
            <h2 className="text-xl font-semibold">Registro de Transacciones</h2>
            <p className="mt-2 text-muted-foreground">
              El equipo de contabilidad se encarga de registrar todas las transacciones comerciales, como ventas,
              compras, pagos y cobros. Esto implica mantener un registro preciso de la actividad financiera de la
              empresa.
            </p>
          </div>
          <div className="p-6 bg-muted rounded-lg">
            <h2 className="text-xl font-semibold">Preparación de Estados Financieros</h2>
            <p className="mt-2 text-muted-foreground">
              A partir de los registros contables, el departamento prepara los estados financieros clave, como el
              balance general, el estado de resultados y el estado de flujos de efectivo. Estos informes proporcionan
              una imagen completa de la situación financiera de la empresa.
            </p>
          </div>
          <div className="p-6 bg-muted rounded-lg">
            <h2 className="text-xl font-semibold">Análisis de Costos</h2>
            <p className="mt-2 text-muted-foreground">
              El equipo de contabilidad realiza un análisis detallado de los costos de la empresa, incluyendo los costos
              de producción, gastos operativos y otros gastos. Esto ayuda a la gerencia a tomar decisiones informadas
              sobre la asignación de recursos y la optimización de los costos.
            </p>
          </div>
          <div className="p-6 bg-muted rounded-lg">
            <h2 className="text-xl font-semibold">Gestión Tributaria</h2>
            <p className="mt-2 text-muted-foreground">
              El departamento de contabilidad es responsable de asegurar el cumplimiento fiscal de la empresa, lo que
              incluye la preparación y presentación de declaraciones de impuestos, así como el cálculo y pago de los
              impuestos correspondientes.
            </p>
          </div>
        </div>
        <div>
          <h2 className="text-xl font-semibold">Informes y Métricas Clave</h2>
          <p className="mt-2 text-muted-foreground">
            El departamento de contabilidad genera una variedad de informes y métricas que ayudan a la gerencia a tomar
            decisiones informadas. Algunos de los informes y métricas más importantes incluyen:
          </p>
          <div className="mt-4 space-y-2 list-disc pl-6 bg-muted p-6 rounded-lg">
            <div>Balance General</div>
            <div>Estado de Resultados</div>
            <div>Estado de Flujos de Efectivo</div>
            <div>Análisis de Rentabilidad</div>
            <div>Ratios Financieros Clave</div>
            <div>Presupuestos y Proyecciones</div>
            <div>Informes de Auditoría</div>
          </div>
        </div>
      </div>
    </div>)
  );
}
