/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/K2IF852XoWk
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function gente_y_cultura() {
  return (
    (<div
      className="flex flex-col items-center justify-center min-h-screen bg-background">
      <div className="max-w-6xl w-full px-4">
        <div className="space-y-4 text-center">
          <h2 className="text-3xl font-bold">Conócenos</h2>
          <p className="text-muted-foreground">
            Conoce a nuestro equipo de expertos que trabajan arduamente para brindar soluciones innovadoras a nuestros
            clientes.
          </p>
        </div>
        <div
          className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8 mt-8">
          <div className="bg-card rounded-lg shadow-lg overflow-hidden">
            <div className="aspect-square">
              <img
                src="/placeholder.svg"
                alt="Employee 1"
                width={400}
                height={400}
                className="object-cover w-full h-full"
                style={{ aspectRatio: "400/400", objectFit: "cover" }} />
            </div>
            <div className="p-4">
              <h3 className="text-xl font-semibold">John Doe</h3>
              <p className="text-muted-foreground">Software Engineer</p>
              <p className="text-sm text-muted-foreground">
                John is a talented software engineer who specializes in building scalable and efficient web
                applications.
              </p>
            </div>
          </div>
          <div className="bg-card rounded-lg shadow-lg overflow-hidden">
            <div className="aspect-square">
              <img
                src="/placeholder.svg"
                alt="Employee 2"
                width={400}
                height={400}
                className="object-cover w-full h-full"
                style={{ aspectRatio: "400/400", objectFit: "cover" }} />
            </div>
            <div className="p-4">
              <h3 className="text-xl font-semibold">Jane Smith</h3>
              <p className="text-muted-foreground">UX Designer</p>
              <p className="text-sm text-muted-foreground">
                Jane is a creative UX designer who crafts intuitive and user-friendly interfaces.
              </p>
            </div>
          </div>
          <div className="bg-card rounded-lg shadow-lg overflow-hidden">
            <div className="aspect-square">
              <img
                src="/placeholder.svg"
                alt="Employee 3"
                width={400}
                height={400}
                className="object-cover w-full h-full"
                style={{ aspectRatio: "400/400", objectFit: "cover" }} />
            </div>
            <div className="p-4">
              <h3 className="text-xl font-semibold">Michael Johnson</h3>
              <p className="text-muted-foreground">Product Manager</p>
              <p className="text-sm text-muted-foreground">
                Michael is a strategic product manager who aligns business goals with user needs.
              </p>
            </div>
          </div>
          <div className="bg-card rounded-lg shadow-lg overflow-hidden">
            <div className="aspect-square">
              <img
                src="/placeholder.svg"
                alt="Employee 4"
                width={400}
                height={400}
                className="object-cover w-full h-full"
                style={{ aspectRatio: "400/400", objectFit: "cover" }} />
            </div>
            <div className="p-4">
              <h3 className="text-xl font-semibold">Emily Davis</h3>
              <p className="text-muted-foreground">Marketing Specialist</p>
              <p className="text-sm text-muted-foreground">
                Emily is a talented marketing specialist who crafts engaging campaigns that drive results.
              </p>
            </div>
          </div>
          <div className="bg-card rounded-lg shadow-lg overflow-hidden">
            <div className="aspect-square">
              <img
                src="/placeholder.svg"
                alt="Employee 5"
                width={400}
                height={400}
                className="object-cover w-full h-full"
                style={{ aspectRatio: "400/400", objectFit: "cover" }} />
            </div>
            <div className="p-4">
              <h3 className="text-xl font-semibold">David Lee</h3>
              <p className="text-muted-foreground">Data Analyst</p>
              <p className="text-sm text-muted-foreground">
                David is a skilled data analyst who transforms complex data into actionable insights.
              </p>
            </div>
          </div>
          <div className="bg-card rounded-lg shadow-lg overflow-hidden">
            <div className="aspect-square">
              <img
                src="/placeholder.svg"
                alt="Employee 6"
                width={400}
                height={400}
                className="object-cover w-full h-full"
                style={{ aspectRatio: "400/400", objectFit: "cover" }} />
            </div>
            <div className="p-4">
              <h3 className="text-xl font-semibold">Sarah Chen</h3>
              <p className="text-muted-foreground">Project Manager</p>
              <p className="text-sm text-muted-foreground">
                Sarah is an experienced project manager who ensures smooth execution and on-time delivery.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>)
  );
}