/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/i1YmwU8Y7WB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function it() {
  return (
    (<div className="w-full max-w-5xl mx-auto px-4 md:px-6 py-12 md:py-16">
      <h1 className="text-4xl font-bold mb-8">Roles y Responsabilidades en un Equipo de TI</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div>
          <h2 className="text-2xl font-bold mb-4">Desarrollo de Software</h2>
          <p className="text-muted-foreground mb-4">
            El equipo de desarrollo de software es responsable de diseñar, codificar, probar y mantener las aplicaciones
            y sistemas que utilizan los usuarios de la organización. Esto incluye tareas como análisis de requisitos,
            diseño de arquitectura, programación, pruebas unitarias y de integración, y despliegue en producción.
          </p>
          <img
            src="/placeholder.svg"
            width={600}
            height={400}
            alt="Software Development"
            className="rounded-lg"
            style={{ aspectRatio: "600/400", objectFit: "cover" }} />
        </div>
        <div>
          <h2 className="text-2xl font-bold mb-4">Administración de Sistemas</h2>
          <p className="text-muted-foreground mb-4">
            El equipo de administración de sistemas es responsable de mantener la infraestructura tecnológica de la
            organización, incluyendo servidores, redes, almacenamiento y sistemas operativos. Esto incluye tareas como
            instalación, configuración, monitoreo, respaldo y recuperación de datos, y resolución de problemas.
          </p>
          <img
            src="/placeholder.svg"
            width={600}
            height={400}
            alt="System Administration"
            className="rounded-lg"
            style={{ aspectRatio: "600/400", objectFit: "cover" }} />
        </div>
        <div>
          <h2 className="text-2xl font-bold mb-4">Seguridad Informática</h2>
          <p className="text-muted-foreground mb-4">
            El equipo de seguridad informática es responsable de proteger los sistemas y datos de la organización contra
            amenazas como malware, ataques cibernéticos y accesos no autorizados. Esto incluye tareas como
            implementación de firewalls, gestión de identidades y accesos, análisis de vulnerabilidades, y respuesta a
            incidentes de seguridad.
          </p>
          <img
            src="/placeholder.svg"
            width={600}
            height={400}
            alt="Cybersecurity"
            className="rounded-lg"
            style={{ aspectRatio: "600/400", objectFit: "cover" }} />
        </div>
        <div>
          <h2 className="text-2xl font-bold mb-4">Soporte Técnico</h2>
          <p className="text-muted-foreground mb-4">
            El equipo de soporte técnico es responsable de asistir a los usuarios finales con problemas o consultas
            relacionadas con la tecnología. Esto incluye tareas como resolución de problemas de hardware y software,
            instalación y configuración de equipos, y capacitación a los usuarios.
          </p>
          <img
            src="/placeholder.svg"
            width={600}
            height={400}
            alt="Technical Support"
            className="rounded-lg"
            style={{ aspectRatio: "600/400", objectFit: "cover" }} />
        </div>
        <div>
          <h2 className="text-2xl font-bold mb-4">Proyectos de Transformación Digital</h2>
          <p className="text-muted-foreground mb-4">
            El equipo de proyectos de transformación digital es responsable de liderar iniciativas que buscan mejorar
            los procesos y servicios de la organización mediante el uso de tecnología. Esto incluye tareas como análisis
            de procesos, diseño de soluciones, gestión de cambio y medición de resultados.
          </p>
          <img
            src="/placeholder.svg"
            width={600}
            height={400}
            alt="Digital Transformation"
            className="rounded-lg"
            style={{ aspectRatio: "600/400", objectFit: "cover" }} />
        </div>
      </div>
    </div>)
  );
}
