/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ZuGqxF8OdV2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Separator } from "@/components/ui/separator"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"

export function perfil() {
  return (
    (<div className="w-full max-w-3xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="bg-background rounded-lg shadow-md p-6">
          <div className="flex items-center gap-4">
            <Avatar className="w-16 h-16">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div>
              <h2 className="text-xl font-semibold">John Doe</h2>
              <p className="text-muted-foreground">johndoe@example.com</p>
            </div>
          </div>
          <Separator className="my-6" />
          <div className="grid gap-4">
            <div>
              <Label htmlFor="bio">Bio</Label>
              <Textarea
                id="bio"
                className="w-full mt-1"
                rows={3}
                defaultValue="I'm a software engineer and I love to code!" />
            </div>
            <div className="flex justify-end">
              <Button size="sm">Update Profile</Button>
            </div>
          </div>
        </div>
        <div className="bg-background rounded-lg shadow-md p-6 space-y-6">
          <div>
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              type="email"
              className="w-full mt-1"
              defaultValue="johndoe@example.com" />
          </div>
          <div>
            <Label htmlFor="password">Password</Label>
            <Input
              id="password"
              type="password"
              className="w-full mt-1"
              defaultValue="********" />
            <p className="text-sm text-muted-foreground">Change your password to secure your account.</p>
          </div>
          <div>
            <Label htmlFor="notification">Notification Settings</Label>
            <Select id="notification" className="w-full mt-1">
              <SelectTrigger>
                <SelectValue placeholder="Select notification settings" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">Receive all notifications</SelectItem>
                <SelectItem value="important">Receive only important notifications</SelectItem>
                <SelectItem value="none">Receive no notifications</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="flex justify-end">
            <Button size="sm">Save Changes</Button>
          </div>
        </div>
      </div>
    </div>)
  );
}
